# Generated by Django 5.2 on 2025-11-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warga',
            name='nik',
        ),
        migrations.AddField(
            model_name='warga',
            name='nim',
            field=models.CharField(default=1, max_length=16, unique=True, verbose_name='Nomor Induk Mahasiswa'),
            preserve_default=False,
        ),
    ]
