# Generated by Django 5.2.7 on 2025-12-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_remove_warga_nik_warga_nim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warga',
            name='nim',
        ),
        migrations.AddField(
            model_name='warga',
            name='nik',
            field=models.CharField(default=0, max_length=16, unique=True, verbose_name='Nomor Induk Kependudukan'),
            preserve_default=False,
        ),
    ]
